### ISSUE TITLE
ModuleNotFoundError: No module named 'pythonjsonlogger

### ISSUE THREAD

**Issue by Ezequiel2342** [SaeidJavadi/Advanced-WhatsApp-Sender#29]
Traceback (most recent call last):
  File "C:\Users\ezequ\OneDrive\Desktop\Advanced-WhatsApp-Sender-main\Advanced-WhatsApp-Sender-main\main.py", line 18, in <module>
    from browserCtrl import Web
  File "C:\Users\ezequ\OneDrive\Desktop\Advanced-WhatsApp-Sender-main\Advanced-WhatsApp-Sender-main\browserCtrl.py", line 28, in <module>
    logging.config.fileConfig(fr"src\logging.ini", disable_existing_loggers=True)
  File "C:\Users\ezequ\AppData\Local\Programs\Python\Python312\Lib\logging\config.py", line 83, in fileConfig
    formatters = _create_formatters(cp)
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ezequ\AppData\Local\Programs\Python\Python312\Lib\logging\config.py", line 132, in _create_formatters
    c = _resolve(class_name)
        ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ezequ\AppData\Local\Programs\Python\Python312\Lib\logging\config.py", line 101, in _resolve
    found = __import__(used)
            ^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'pythonjsonlogger'

hi, i was installing all the missing modules with pip install -U "module" but, i had a problem with this module named, "pythonjsonlogger"

**Comment by Ziakimbogo** [comment]
pip install python-json-logger

**Comment by SaeidJavadi** [comment]
Hello
Use this command to install prerequisites
`pip install python-json-logger`
