### ISSUE TITLE
TypeError: not all arguments converted during string formatting

### ISSUE THREAD

**Issue by syedawaisamjad** [SaeidJavadi/Advanced-WhatsApp-Sender#34]
The program runs and opens chrome just fine. Upon Starting Chat it crashes and gives this stack trace:, I have added a fictitious number in the post for obvious reasons, I use the correct number when I run the program.

--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\Admin\anaconda3\lib\logging\handlers.py", line 668, in emit
    s = self.makePickle(record)
  File "C:\Users\Admin\anaconda3\lib\logging\handlers.py", line 635, in makePickle
    d['msg'] = record.getMessage()
  File "C:\Users\Admin\anaconda3\lib\logging\__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "C:\bulk_msg\Advanced-WhatsApp-Sender-main\browserCtrl.py", line 404, in run
    self.SendTEXT()
  File "C:\bulk_msg\Advanced-WhatsApp-Sender-main\browserCtrl.py", line 261, in SendTEXT
    log.debug("find", num)
Message: 'find'
Arguments: (923331111111)
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\Admin\anaconda3\lib\logging\__init__.py", line 1083, in emit
    msg = self.format(record)
  File "C:\Users\Admin\anaconda3\lib\logging\__init__.py", line 927, in format
    return fmt.format(record)
  File "C:\Users\Admin\anaconda3\lib\logging\__init__.py", line 663, in format
    record.message = record.getMessage()
  File "C:\Users\Admin\anaconda3\lib\logging\__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "C:\bulk_msg\Advanced-WhatsApp-Sender-main\browserCtrl.py", line 404, in run
    self.SendTEXT()
  File "C:\bulk_msg\Advanced-WhatsApp-Sender-main\browserCtrl.py", line 261, in SendTEXT
    log.debug("find", num)
  File "C:\Users\Admin\anaconda3\lib\logging\__init__.py", line 1434, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "C:\Users\Admin\anaconda3\lib\logging\__init__.py", line 1589, in _log
    self.handle(record)
  File "C:\Users\Admin\anaconda3\lib\logging\__init__.py", line 1599, in handle
    self.callHandlers(record)
  File "C:\Users\Admin\anaconda3\lib\logging\__init__.py", line 1661, in callHandlers
    hdlr.handle(record)
  File "C:\Users\Admin\anaconda3\lib\logging\__init__.py", line 952, in handle
    self.emit(record)
  File "C:\bulk_msg\Advanced-WhatsApp-Sender-main\src\logcolor.py", line 70, in new
    ret = fn(*args)
Message: 'find'
Arguments: (923331111111)
[2024-05-26 14:35:43,606][DEBUG] end msg
[2024-05-26 14:35:43,606][DEBUG] stopping thread...

------------------ Can you please look into this and tell me what to do.. thanks

**Comment by Aman9392** [comment]
Hi , I am getting Same Error Can You Please Look in the issue OR may be give some Sugesstions so we can solve it 

"TypeError: not all arguments converted during string formatting"

**Comment by SaeidJavadi** [comment]
Hi @Aman9392 @syedawaisamjad 
I just wanted to let you know that I’ve updated the Advanced WhatsApp Sender project.
Sorry it took a bit longer this time
I was busy with other projects, but I finally managed to complete the update
If you notice any issues, please send me the app.log file or report it so I can fix it.
Please make sure to install all the prerequisites correctly by following the instructions
